server:
  port: 8080

spring:
  application:
    name: game-store-service
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
        - 10.0
  datasource:
    #url: jdbc:h2:file:./gamestoreDB;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    #driverClassName: org.h2.Driver
    #username: sa
    #password: password
    url: jdbc:mysql://game-store.cg8j1mqqwm9z.us-east-2.rds.amazonaws.com:3306/game_store?useSSL=false&serverTimezone=US/Eastern&allowPublicKeyRetrieval=true
    username: root
    password: rootroot
  jpa:
    #generate-ddl: true
    #database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      #eureka-server is the name of the docker container running the eureka server instance
      defaultZone: http://localhost:8761/eureka/
  instance:
    #eureka-server is the name of the docker container running the eureka server instance
    hostname: localhost
